name : upload website to S3 
on: 
  push: 
    branches:
    - main

jobs: 
  deploy:
    runs-on:ubunto-latest
    steps:
    -uses: actions/checkout@master
    -uses: jakejarvis/s3-sync-action@master
  with:
    args: --acl public-read --follow-symlinks --delete
  env:
    AWS_S3_BUCKET: ${{secrects.AWS_S3_BUCKET}}
    AWS_ACCESS_KEY_ID: ${{secrects.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    AWS_REGION: 'Europe (Paris) eu-west-3'
    SOURCE_DIR: 'cloud-resume-challenge'
